<?php

/**
 * @file
 * Send to friends module main file.
 */

/**
 * Implements of hook_permission().
 */
function send_to_friends_permission() {
  return array(
    'use send to friends form' => array(
      'title' => t('Use Send To Friends'),
      'description' => t('Use Send To Friends Form'),
    ),
  );
}

/**
 * Implements of hook_menu().
 */
function send_to_friends_menu() {
  $items = array();

  $items['admin/config/content/send_to_friends'] = array(
    'title'            => 'Send to friends',
    'description'      => 'Manage Send to friends e-mail messages',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('send_to_friends_general_settings'),
    'access callback'  => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file'             => 'send_to_friends.admin.inc',
    'file path'        => drupal_get_path('module', 'send_to_friends'),
  );

  $items['send-form'] = array(
    'title'            => 'Send to friends',
    'description'      => 'Page with send to friends form',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('send_to_friends_form'),
    'access callback'  => 'user_access',
    'access arguments' => array('use send to friends form'),
  );

  $items['send-to-friends/%ctools_js/form'] = array(
    'title'             => 'Send to friends',
    'page callback'     => 'send_to_friends_page_callback',
    'page arguments'    => array(1),
    'access arguments'  => array('use send to friends form'),
    'delivery callback' => 'ajax_deliver',
    'theme callback'    => 'ajax_base_page_theme',
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function send_to_friends_block_info() {
  $blocks['send_to_friends'] = array(
    'info'  => t('Send to friends form'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function send_to_friends_block_view($delta = '') {
  $blocks = array();

  if (user_access('use send to friends form') && $delta == 'send_to_friends') {
    // Include js libraries, add setting for modal window.
    SendToFriends::ModalFormSettings();
    $blocks['content'] = ctools_modal_text_button(variable_get('send_to_friends_link_text', t('Send this page to your friends')), 'send-to-friends/nojs/form/', t('Send to friends'), 'ctools-modal-sent-to-friends-style');
  }
  return $blocks;
}

/**
 * Page call back for calling modal window.
 *
 * @param mixed $js
 *   ctools variable that check js status on browser.
 *
 * @return array
 *   commands for modal window.
 */
function send_to_friends_page_callback($js = NULL) {
  if (!$js) {
    // If js is disabled show message about it.
    drupal_set_message(t("Enable javascript on your browser please."));
    drupal_goto($_SERVER['HTTP_REFERER']);
  }

  // Include library.
  ctools_include('modal');

  $form_state = array(
    'title' => t('Send to friends'),
    'ajax' => TRUE,
    'build_info' => array(
      'args' => array(),
    ),
  );

  // Include 'send to friend' from.
  form_load_include($form_state, 'inc', 'send_to_friends', 'send_to_friends.form');

  $commands = array();
  $commands = ctools_modal_form_wrapper('send_to_friends_form', $form_state);
  $commands[] = ajax_command_invoke(".send_to_friends_page_path", 'send_to_friends_set_page_path');

  if (!empty($form_state['executed'])) {

    $thy_message_status = variable_get('send_to_friends_thanks_message_in_popup', 'popup');
    $commands = array();
    if ($thy_message_status == 'popup') {
      $commands[] = ajax_command_replace('.send-to-friends-form', variable_get('send_to_friends_thanks_message', t("Thank you.")));
      // Simulate a message showing that it will not show after page reload
      // on this step we have not '.send-to-friends-form' class.
      $commands[] = ajax_command_prepend('.send-to-friends-form', theme('status_messages'));
    }
    elseif ($thy_message_status == 'status') {
      $commands[] = ajax_command_prepend('#content', theme('status_messages'));
      $commands[] = ctools_modal_command_dismiss();
    }
  }
  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Implements hook_mail().
 *
 * @param string $key
 *   Identifier of the mail.
 * @param array $message
 *   Sending data.
 * @param array $params
 *   An array of parameters.
 */
function send_to_friends_mail($key, &$message, $params) {
  if ($key == "send_to_friends") {
    $message['subject'] = $params['subject'];
    $message['body'][]  = $params['body'];
    $message['headers'] = array_merge($message['headers'], $params['headers']);
  }
}

/**
 * Implements hook_mollom_form_list().
 */
function send_to_friends_mollom_form_list() {
  $forms['send_to_friends_form'] = array(
    'title' => t('Send to friends form'),
  );
  return $forms;
}

/**
 * Implemenents hook_mollom_form_info().
 */
function send_to_friends_mollom_form_info($form_id) {
  switch ($form_id) {
    case 'send_to_friends_form':
      $form_info = array(
        'elements' => array(
          'friend_name' => t("Friend's Name"),
          'send-to-friends-mail' => t("Friend's E-mail Address"),
          'sender_name' => t('Your name'),
        ),
      );
      break;
  }
  return $form_info;
}
